### ISSUE TITLE
Cannot archive project

### ISSUE THREAD

**Issue by gauuni** [dekatotoro/SlideMenuControllerSwift#314]
<img width="1440" alt="screen shot 2017-04-21 at 4 25 36 pm" src="https://cloud.githubusercontent.com/assets/6175053/25271706/39c6c396-26af-11e7-8b66-af97c637f72a.png">
Hi,
Please help me out, I use your lib in my project, when I build directly to my device, it works fine. Then I archive project, it show these errors.
Please check and tell me soon.
Thank you very much

**Comment by gauuni** [comment]
Ya, I still don't know why, but I removed it from cocoapod, get swift file and add manually in my project. 
It worked.

**Comment by ahsyarif008** [comment]
hello @gauuni . i just do removing from cocoapods and add it manually, but the error is still occured (still same as your screnshoot "apple link mach-o")

can you help me how you import it manually. here is my config. thanks. hope you help me please..
![screen shot 2017-05-02 at 11 28 15 am](https://cloud.githubusercontent.com/assets/11441542/25603925/84f8f2a2-2f2a-11e7-8ec9-3a4a3231aec2.png)

**Comment by gauuni** [comment]
What did you add in your project? I only added SlideMenuController.swift file, and didn't add anything to embedded binaries

**Comment by ahsyarif008** [comment]
i add entire repo in my project like the alamofire manual step said. hehehe.

but if you only add just a single file "SlideMenuController.swift" file, how can you implement "import SlideMenuControllerSwift". it will asking for references and can by done by importing "SlideMenuControllerSwift.framework.

**Comment by gauuni** [comment]
When you add it manually, needn't "import SlideMenuControllerSwift". Now it's just a swift class, not framework anymore. Do you know that?

**Comment by ahsyarif008** [comment]
Emm. so we work with class only. not as framework. okay, I 'll try. I thinks i am understand. thanks @gauuni  :)

**Comment by gauuni** [comment]
You're welcome. Hope can help you ressolve your problem

**Comment by ahsyarif008** [comment]
thanks so much @gauuni . my problem is solved :)

**Comment by Mikael491** [comment]
@ahsyarif008 I added whole repo to my project as well but still cannot get it to compile for archive

**Comment by Mikael491** [comment]
@ahsyarif008 please help

**Comment by Mikael491** [comment]
Solved ✔️✔️
